#
# Copyright (C) 2017 DANS - Data Archiving and Networked Services (info@dans.knaw.nl)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Configure bag stores
  lineinfile:
      dest: "{{ dans_config_base }}/easy-bag-store/stores.properties"
      line: "{{ item.name }}={{ item.base_dir }}"
  with_items: "{{ bag_stores }}"

- name: Create empty bag-store base directories
  file:
    path: "{{ stores_dir }}/{{ item.name }}"
    state: "directory"
    owner: "easy-bag-store"
    group: "easy-bag-store"
    mode: "0775"
  with_items: "{{ bag_stores }}"

- name: Create link to test data
  file:
    src: /vagrant/src/test/resources/vault/stores/pdbs/bags
    dest: /home/vagrant/test-data
    state: link
